platform :ios, '9.0'

target 'TODO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TODO
  pod 'RealmSwift'
  pod 'SwipeCellKit'

end
